AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 10

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/Lambda:
  EnforcedStyle: literal

Style/IfInsideElse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
